---
- name: Install httpd server ansible nodes 
  become: yes
  hosts: webservers

  tasks:
   - name: install httpd server
     yum:
      name: httpd
      state: installed
      
   - name: start httpd service and enabled
     service:
       name: httpd
       state: started
       enabled: yes


   - name: create index.html file
     copy:
       content: <h1> Httpd service installed on host {{inventory_hostname}}<h1>
       dest: /var/www/html/index.html


#once we write the playbook we can run this playbook by giving below command

#ansible-playbook -i <ansible-inventory-file> <playbook-file-name>
#ansible-playbook -i inventory.ini install_httpd.yml